POST http://localhost:5000/addclients
Content-Type: application/json

{
    "id": 10,
    "firstname": "firstname",
    "lastname": "lastname",
    "email": "email",
    "password": "password"
}